version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decantre-backend-dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /var/www/uploads:/app/uploads
