export const CATEGORY_METADATA = [
  {
    id: 'shirts',
    name: 'Shirts',
    slug: 'shirts',
    tagline: 'Italian poplin, Mulberry silk & draped resort tailoring',
    description: 'Precision-crafted luxury shirts built with architectural collars, relaxed drops, and high-thread count European fabrics.',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=1200',
    itemCount: '4 Garments'
  },
  {
    id: 'jeans',
    name: 'Jeans',
    slug: 'jeans',
    tagline: 'Japanese selvedge, sun-bleached washes & classic cuts',
    description: 'Artisanal denim woven on vintage shuttle looms in Okayama, finished with hand-fading and debossed hardware.',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=1200',
    itemCount: '4 Garments'
  },
  {
    id: 'denim',
    name: 'Denim',
    slug: 'denim',
    tagline: 'Heavyweight trucker jackets, workwear vests & overshirts',
    description: 'Architectural denim outer layers engineered from 14oz-18oz raw and washed denim for structured durability.',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=1200',
    itemCount: '4 Garments'
  },
  {
    id: 'baggy',
    name: 'Baggy',
    slug: 'baggy',
    tagline: 'Oversized double-pleated trousers, cargo pants & wide denim',
    description: 'Voluminous silhouettes featuring extended rise, deep double pleats, and fluid drape engineered for comfort and modern streetwear elegance.',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=1200',
    itemCount: '4 Garments'
  },
  {
    id: 'long-sleeve-t-shirt',
    name: 'Long Sleeve T-Shirt',
    slug: 'long-sleeve-t-shirt',
    tagline: 'Heavyweight mocknecks, thermal waffle weaves & thumbhole cuts',
    description: 'Essential long sleeve foundations crafted from 350GSM combed organic cotton with reinforced ribbing.',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&q=80&w=1200',
    itemCount: '4 Garments'
  },
  {
    id: 'short-sleeve-t-shirt',
    name: 'Short Sleeve T-Shirt',
    slug: 'short-sleeve-t-shirt',
    tagline: 'Boxy 300GSM organic cotton tees, garment-dyed & embroidered',
    description: 'Minimalist streetwear staples featuring drop-shoulder proportions, high-density cotton, and soft vintage washes.',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1200',
    itemCount: '4 Garments'
  }
];

export const PRODUCTS = [
  // --- SHIRTS ---
  {
    id: 'sh-01',
    name: 'Oversized Italian Poplin Shirt',
    tagline: 'Crisp 100% Thomas Mason cotton poplin with dropped shoulders',
    price: 2450,
    originalPrice: 2950,
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 42,
    category: 'Shirts',
    categorySlug: 'shirts',
    gender: 'Unisex',
    colors: [
      { name: 'Optic White', hex: '#ffffff' },
      { name: 'Onyx Black', hex: '#111111' },
      { name: 'Sky Blue', hex: '#a2c4e0' }
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 18,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=1000',
    description: 'Crafted from high-density Italian cotton poplin. Features an exaggerated boxy body, elongated mother-of-pearl buttons, and structured cuffs.',
    fabric: '100% Organic Italian Cotton Poplin',
    care: 'Machine wash cold delicate. Iron low or dry clean.',
    fit: 'Generous oversized fit. True to runway sizing.'
  },
  {
    id: 'sh-02',
    name: 'Draped Mulberry Silk Camp Shirt',
    tagline: 'Fluid 19mm Mulberry silk with resort cuban collar',
    price: 3200,
    originalPrice: 3800,
    isNew: true,
    isBestSeller: false,
    rating: 5.0,
    reviewsCount: 29,
    category: 'Shirts',
    categorySlug: 'shirts',
    gender: 'Unisex',
    colors: [
      { name: 'Champagne Silk', hex: '#e8dcbe' },
      { name: 'Midnight Black', hex: '#0a0a0a' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 12,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=1000',
    description: 'Ultra-luxurious Mulberry silk woven with subtle luster. The relaxed camp collar and side hem vents create effortless movement.',
    fabric: '100% Pure Mulberry Silk',
    care: 'Dry clean only. Do not tumble dry.',
    fit: 'Relaxed draped silhouette.'
  },
  {
    id: 'sh-03',
    name: 'Minimalist Linen Utility Resort Shirt',
    tagline: 'Breathable Normandy flax linen with dual chest patch pockets',
    price: 1950,
    originalPrice: 2250,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 35,
    category: 'Shirts',
    categorySlug: 'shirts',
    gender: 'Men',
    colors: [
      { name: 'Raw Natural Linen', hex: '#d9cdbe' },
      { name: 'Olive Drab', hex: '#4f543e' }
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    stockCount: 15,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&q=80&w=1000',
    description: 'Garment-washed Normandy flax linen designed for maximum breathability during warmer seasons with tactile textured weave.',
    fabric: '100% French Normandy Flax Linen',
    care: 'Hand wash or gentle cold machine wash. Line dry.',
    fit: 'Relaxed utility fit.'
  },
  {
    id: 'sh-04',
    name: 'Sartorial Band Collar Oxford Shirt',
    tagline: 'Tailored grandad collar shirt with concealed front placket',
    price: 2100,
    originalPrice: 2100,
    isNew: false,
    isBestSeller: false,
    rating: 4.7,
    reviewsCount: 19,
    category: 'Shirts',
    categorySlug: 'shirts',
    gender: 'Men',
    colors: [
      { name: 'Slate Gray', hex: '#585e68' },
      { name: 'Pure White', hex: '#ffffff' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 10,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=1000',
    description: 'Clean architectural lines with a minimalist band collar. Ideal for layering under tailoring or wearing standalone.',
    fabric: '100% Combed Oxford Cotton',
    care: 'Machine wash warm, tumble dry low.',
    fit: 'Modern tailored fit.'
  },

  // --- JEANS ---
  {
    id: 'jn-01',
    name: 'Straight Leg Vintage Wash Selvedge Jeans',
    tagline: '14.5oz Okayama selvedge denim with natural whiskering',
    price: 2850,
    originalPrice: 3400,
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 64,
    category: 'Jeans',
    categorySlug: 'jeans',
    gender: 'Unisex',
    colors: [
      { name: 'Vintage Wash Indigo', hex: '#2b4162' },
      { name: 'Washed Charcoal', hex: '#2c2d30' }
    ],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
    stockCount: 22,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&q=80&w=1000',
    description: 'Woven on vintage shuttle looms in Kurashiki, Japan. Features hand-worked abrasion detailing, custom red selvedge ID, and matte black rivets.',
    fabric: '100% Japanese Selvedge Cotton Denim',
    care: 'Wash cold inside out. Hang dry to retain indigo gradient.',
    fit: 'Mid-rise classic straight leg.'
  },
  {
    id: 'jn-02',
    name: 'Raw Indigo Kuroki Mills Tapered Jeans',
    tagline: 'Unwashed 16oz stiff Japanese raw denim with red selvedge line',
    price: 3100,
    originalPrice: 3100,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 48,
    category: 'Jeans',
    categorySlug: 'jeans',
    gender: 'Men',
    colors: [
      { name: 'Raw Deep Indigo', hex: '#16233b' }
    ],
    sizes: ['30', '32', '34', '36'],
    inStock: true,
    stockCount: 9,
    image: 'https://images.unsplash.com/photo-1542272604-780c36856842?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?auto=format&fit=crop&q=80&w=1000',
    description: 'Unprocessed heavy raw denim built to mold to your body over time, developing personalized honeycomb and whiskering fades.',
    fabric: '100% Raw Selvedge Cotton',
    care: 'Soak cold after 6 months of wear for bespoke fading.',
    fit: 'Tapered athletic fit.'
  },
  {
    id: 'jn-03',
    name: 'Sun-Bleached Washed Grey Denim Jeans',
    tagline: 'Stone-washed 13oz grey denim with distressed hem',
    price: 2650,
    originalPrice: 2950,
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviewsCount: 31,
    category: 'Jeans',
    categorySlug: 'jeans',
    gender: 'Unisex',
    colors: [
      { name: 'Sun-Bleached Grey', hex: '#7a7f85' },
      { name: 'Faded Black', hex: '#1f2022' }
    ],
    sizes: ['28', '30', '32', '34'],
    inStock: true,
    stockCount: 14,
    image: 'https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=1000',
    description: 'Acid stone-washed treatment giving an authentic vintage grunge aesthetic with soft worn-in handfeel from day one.',
    fabric: '100% Ring-Spun Cotton Denim',
    care: 'Machine wash cold with like colors.',
    fit: 'Relaxed straight fit.'
  },
  {
    id: 'jn-04',
    name: 'Classic Mid-Rise Indigo Denim Jeans',
    tagline: 'Timeless 5-pocket denim with contrast tan stitching',
    price: 2350,
    originalPrice: 2350,
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 22,
    category: 'Jeans',
    categorySlug: 'jeans',
    gender: 'Unisex',
    colors: [
      { name: 'Classic Blue Indigo', hex: '#203961' }
    ],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
    stockCount: 16,
    image: 'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1542272604-780c36856842?auto=format&fit=crop&q=80&w=1000',
    description: 'The quintessential 5-pocket denim cut. High waist stability and durable copper rivets for everyday wear.',
    fabric: '99% Organic Cotton, 1% Elastane',
    care: 'Machine wash cold, tumble dry low.',
    fit: 'Standard mid-rise regular cut.'
  },

  // --- DENIM ---
  {
    id: 'dn-01',
    name: 'Monolith Raw Denim Trucker Jacket',
    tagline: 'Heavyweight 16oz Kuroki selvedge jacket with boxy cut',
    price: 4200,
    originalPrice: 4800,
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 57,
    category: 'Denim',
    categorySlug: 'denim',
    gender: 'Unisex',
    colors: [
      { name: 'Raw Indigo', hex: '#1a2b4c' },
      { name: 'Pitch Black', hex: '#0f0f10' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 11,
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=1000',
    description: 'Constructed from rigid Japanese selvedge denim. Boxy cropped silhouette with concealed chest pockets and custom Engulfic debossed hardware.',
    fabric: '100% Japanese Selvedge Cotton Denim',
    care: 'Dry clean or cold hand wash.',
    fit: 'Boxy cropped modern silhouette.'
  },
  {
    id: 'dn-02',
    name: 'Raw Denim Utility Chore Coat',
    tagline: '4-pocket industrial chore jacket with corduroy collar',
    price: 3600,
    originalPrice: 3600,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 39,
    category: 'Denim',
    categorySlug: 'denim',
    gender: 'Men',
    colors: [
      { name: 'Washed Denim Blue', hex: '#314c73' },
      { name: 'Tobacco Brown', hex: '#5c4128' }
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    stockCount: 13,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=1000',
    description: 'Classic French workwear coat interpreted in heavy denim. Contrast brown corduroy collar and reinforced triple-needle stitching.',
    fabric: '100% Heavy Cotton Denim & Corduroy Collar',
    care: 'Machine wash cold.',
    fit: 'Relaxed workwear fit.'
  },
  {
    id: 'dn-03',
    name: 'Distressed Denim Overshirt',
    tagline: 'Lightweight 10oz washed denim shirt jacket',
    price: 2850,
    originalPrice: 3200,
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviewsCount: 28,
    category: 'Denim',
    categorySlug: 'denim',
    gender: 'Unisex',
    colors: [
      { name: 'Faded Sky Indigo', hex: '#6b8fb3' }
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 17,
    image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=1000',
    description: 'Versatile transitional piece. Wear it buttoned as a heavy shirt or unbuttoned over a white tee.',
    fabric: '100% Softened Cotton Denim',
    care: 'Machine wash cold.',
    fit: 'Relaxed overshirt drape.'
  },
  {
    id: 'dn-04',
    name: 'Sculptural Denim Workwear Vest',
    tagline: 'Sleeveless padded denim vest with 3D tactical bellows pockets',
    price: 2450,
    originalPrice: 2800,
    isNew: false,
    isBestSeller: false,
    rating: 4.8,
    reviewsCount: 21,
    category: 'Denim',
    categorySlug: 'denim',
    gender: 'Unisex',
    colors: [
      { name: 'Washed Charcoal', hex: '#2b2c2e' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 8,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=1000',
    description: 'Tactical streetwear layer with heavy YKK zips and bellows flap pockets for functional utility.',
    fabric: '100% Cotton Washed Denim',
    care: 'Machine wash cold gentle.',
    fit: 'Boxy layering vest.'
  },

  // --- BAGGY ---
  {
    id: 'bg-01',
    name: 'Baggy Pleated Architectural Trousers',
    tagline: 'Double-pleated wide-leg trousers with extended waist tab',
    price: 3500,
    originalPrice: 4200,
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 73,
    category: 'Baggy',
    categorySlug: 'baggy',
    gender: 'Unisex',
    colors: [
      { name: 'Deep Onyx', hex: '#0f0f10' },
      { name: 'Charcoal Houndstooth', hex: '#34383c' },
      { name: 'Taupe Stone', hex: '#8c857b' }
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 24,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&q=80&w=1000',
    description: 'Engineered with deep front pleats and a voluminous wide leg that breaks effortlessly over boots or chunky sneakers. Side cinch adjusters ensure a custom fit.',
    fabric: '80% Tropical Wool, 20% Technical Viscose',
    care: 'Dry clean recommended.',
    fit: 'High-waisted, voluminous wide leg drape.'
  },
  {
    id: 'bg-02',
    name: 'Oversized Baggy Skate Pants',
    tagline: 'Extra-wide leg heavy twill trousers with hammer loop',
    price: 2750,
    originalPrice: 2750,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 51,
    category: 'Baggy',
    categorySlug: 'baggy',
    gender: 'Unisex',
    colors: [
      { name: 'Washed Army Green', hex: '#3d4533' },
      { name: 'Pitch Black', hex: '#111111' }
    ],
    sizes: ['30', '32', '34', '36'],
    inStock: true,
    stockCount: 19,
    image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=1000',
    description: '90s skate culture reinvented through luxury tailoring. Heavy 12oz cotton twill with reinforced knee paneling and drawstring waist.',
    fabric: '100% Heavy Cotton Twill',
    care: 'Machine wash cold inside out.',
    fit: 'Ultra baggy relaxed rise.'
  },
  {
    id: 'bg-03',
    name: 'Wide-Leg Baggy Denim Cargo Pants',
    tagline: 'Voluminous 6-pocket denim trousers with adjustable ankle cinches',
    price: 3250,
    originalPrice: 3750,
    isNew: true,
    isBestSeller: false,
    rating: 5.0,
    reviewsCount: 37,
    category: 'Baggy',
    categorySlug: 'baggy',
    gender: 'Unisex',
    colors: [
      { name: 'Washed Black Denim', hex: '#222326' },
      { name: 'Bleached Light Blue', hex: '#a6c0db' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 16,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=1000',
    description: 'Substantial 3D utility cargo pockets on a wide baggy denim frame. Drawstring hem ties allow converting from baggy straight leg to cinched balloon leg.',
    fabric: '100% Cotton Denim',
    care: 'Machine wash cold line dry.',
    fit: 'Convertible baggy balloon fit.'
  },
  {
    id: 'bg-04',
    name: 'Relaxed Heavyweight Baggy Sweatpants',
    tagline: '500GSM french terry wide-leg sweatpants with hidden zip pockets',
    price: 2200,
    originalPrice: 2200,
    isNew: false,
    isBestSeller: false,
    rating: 4.8,
    reviewsCount: 44,
    category: 'Baggy',
    categorySlug: 'baggy',
    gender: 'Unisex',
    colors: [
      { name: 'Washed Vintage Grey', hex: '#63676e' },
      { name: 'Chalk White', hex: '#f0ede6' }
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    stockCount: 22,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&q=80&w=1000',
    description: 'Ultra-heavyweight loungewear executed with tailored wide-leg proportions. Unribbed open hem line.',
    fabric: '100% Combed Organic Cotton French Terry',
    care: 'Machine wash cold inside out.',
    fit: 'Baggy open-hem drape.'
  },

  // --- LONG SLEEVE T-SHIRT ---
  {
    id: 'ls-01',
    name: 'Heavyweight Mockneck Long Sleeve T-Shirt',
    tagline: '350GSM combed organic cotton with 2-inch rib mock collar',
    price: 1450,
    originalPrice: 1800,
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 68,
    category: 'Long Sleeve T-Shirt',
    categorySlug: 'long-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Pitch Black', hex: '#101010' },
      { name: 'Bone Off-White', hex: '#ece8de' },
      { name: 'Forest Shadow', hex: '#203326' }
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    stockCount: 30,
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=1000',
    description: 'Structured architectural base layer. Dense 350GSM organic cotton preserves its mockneck shape wear after wear.',
    fabric: '100% Combed Organic Cotton Jersey',
    care: 'Machine wash cold inside out. Flat dry.',
    fit: 'Boxy athletic drape.'
  },
  {
    id: 'ls-02',
    name: 'Waffle-Knit Layering Long Sleeve Tee',
    tagline: 'Thermal textured waffle cotton with curved drop-tail hem',
    price: 1350,
    originalPrice: 1600,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 42,
    category: 'Long Sleeve T-Shirt',
    categorySlug: 'long-sleeve-t-shirt',
    gender: 'Men',
    colors: [
      { name: 'Charcoal Slub', hex: '#313338' },
      { name: 'Oatmeal Beige', hex: '#ded6c8' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 21,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&q=80&w=1000',
    description: 'Tactile honeycomb waffle weave designed for temperature regulation and subtle texture layering under coats or jackets.',
    fabric: '100% Thermal Cotton Waffle',
    care: 'Machine wash cold with gentle detergent.',
    fit: 'Slim contour layering fit.'
  },
  {
    id: 'ls-03',
    name: 'Avant-Garde Thumbhole Long Sleeve Tee',
    tagline: 'Seamless double-layer cuffs with discrete thumb slots',
    price: 1650,
    originalPrice: 1650,
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviewsCount: 19,
    category: 'Long Sleeve T-Shirt',
    categorySlug: 'long-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Pure Obsidian', hex: '#080808' },
      { name: 'Washed Olive', hex: '#444a38' }
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 14,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&q=80&w=1000',
    description: 'Elongated sleeves featuring built-in thumbhole slits for modern darkwear and urban utility aesthetics.',
    fabric: '95% Micro-Modal Cotton, 5% Elastane',
    care: 'Machine wash delicate cold.',
    fit: 'Body skimming elongated fit.'
  },
  {
    id: 'ls-04',
    name: 'Raw Edge Vintage Wash Long Sleeve Tee',
    tagline: 'Acid garment-dyed cotton with raw cut neckline',
    price: 1550,
    originalPrice: 1750,
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviewsCount: 26,
    category: 'Long Sleeve T-Shirt',
    categorySlug: 'long-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Vintage Sun-Faded Black', hex: '#242528' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 16,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
    description: 'Individually hand-dyed to achieve a unique sun-faded patina with unhemmed raw edges that gently roll.',
    fabric: '100% Ring-Spun Cotton',
    care: 'Wash cold inside out separately.',
    fit: 'Relaxed vintage drape.'
  },

  // --- SHORT SLEEVE T-SHIRT ---
  {
    id: 'ss-01',
    name: 'Minimalist Boxy 300GSM Short Sleeve T-Shirt',
    tagline: 'Heavyweight combed cotton tee with drop-shoulder cut',
    price: 1050,
    originalPrice: 1350,
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 112,
    category: 'Short Sleeve T-Shirt',
    categorySlug: 'short-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Onyx Black', hex: '#111111' },
      { name: 'Chalk White', hex: '#f7f5ed' },
      { name: 'Concrete Gray', hex: '#8a8e94' }
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    stockCount: 45,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=1000',
    description: 'The definitive daily luxury T-shirt. Substantial 300GSM weight holds its boxy structure throughout the day without clinging.',
    fabric: '100% Combed Organic Cotton (300GSM)',
    care: 'Machine wash cold inside out with like colors.',
    fit: 'Boxy drop-shoulder streetwear fit.'
  },
  {
    id: 'ss-02',
    name: 'Raised Embroidery Signature Short Sleeve Tee',
    tagline: 'Tone-on-tone 3D puff chest embroidery with high ribbed collar',
    price: 1200,
    originalPrice: 1200,
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    reviewsCount: 84,
    category: 'Short Sleeve T-Shirt',
    categorySlug: 'short-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Washed Olive Drab', hex: '#3d4234' },
      { name: 'Pitch Black', hex: '#0f0f10' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 28,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
    description: 'Features a subtle tactile 3D rubberized logo print on the chest with reinforced high-density neck collar.',
    fabric: '100% Premium Cotton Jersey',
    care: 'Machine wash cold inside out.',
    fit: 'Relaxed modern fit.'
  },
  {
    id: 'ss-03',
    name: 'Garment-Dyed Vintage Oversized Tee',
    tagline: 'Softened vintage washed cotton with faded seam detail',
    price: 1150,
    originalPrice: 1300,
    isNew: false,
    isBestSeller: false,
    rating: 4.7,
    reviewsCount: 53,
    category: 'Short Sleeve T-Shirt',
    categorySlug: 'short-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Vintage Slate Blue', hex: '#415263' },
      { name: 'Washed Espresso', hex: '#3b2f29' }
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 19,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
    description: 'Pre-shrunk enzyme washed tee offering supreme softness and an authentic lived-in patina.',
    fabric: '100% Enzyme-Washed Cotton',
    care: 'Machine wash cold line dry.',
    fit: 'Oversized boxy cut.'
  },
  {
    id: 'ss-04',
    name: 'Sculptural Drop Shoulder Heavyweight Tee',
    tagline: 'Extended elbow sleeve cut in 320GSM compact jersey',
    price: 1250,
    originalPrice: 1500,
    isNew: true,
    isBestSeller: false,
    rating: 4.9,
    reviewsCount: 38,
    category: 'Short Sleeve T-Shirt',
    categorySlug: 'short-sleeve-t-shirt',
    gender: 'Unisex',
    colors: [
      { name: 'Bone White', hex: '#f0ece1' },
      { name: 'Raw Black', hex: '#141414' }
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    stockCount: 15,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=1000',
    secondaryImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
    description: 'Architectural silhouette with wide elbow-length sleeves and high collar construction for elevated styling.',
    fabric: '100% Compact Spun Organic Cotton',
    care: 'Dry clean or cold wash inside out.',
    fit: 'Sculptural oversized drop shoulder.'
  }
];

export const CATEGORIES = [
  'All',
  'Shirts',
  'Jeans',
  'Denim',
  'Baggy',
  'Long Sleeve T-Shirt',
  'Short Sleeve T-Shirt'
];
